Repository solop-develop/frontend-core, pull requests merged in 2022-05, with the labels that each got.

#29 fix: Field zoom to window.
  src/api/ADempiere/field/locator.js
  src/api/ADempiere/user-interface/persistence.js
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: bug

#42 docs: Add process open.
  docs/.vuepress/config.js
  docs/.vuepress/public/images/use-cases/process-menu-lookup-vue.mp4
  docs/.vuepress/public/images/use-cases/process-menu-lookup-zk.mp4
  docs/.vuepress/public/images/use-cases/process-recent-items-vue.mp4
  docs/.vuepress/public/images/use-cases/process-relations-vue.mp4
  docs/.vuepress/public/images/use-cases/process-window-vue.mp4
  docs/.vuepress/public/images/use-cases/process-window-zk.mp4
  docs/es/guide/use-cases/process.md
  docs/guide/use-cases/process.md
Labels: documentation

#40 Update README.es.md
  README.es.md
Labels: documentation

#44 fix: Docs path.
  docs/.vuepress/config.js
Labels: documentation

#49 correct error when loading the panel in the processes
  src/utils/ADempiere/dictionary/window.js
  src/views/ADempiere/Window/index.vue
Labels: bug

#50 Add report actions to menu
  src/views/ADempiere/ReportViewer/index.vue
Labels: bug

#73 fix: Docs video width in mobile.
  docs/es/guide/use-cases/process.md
Labels: bug, documentation

#86 feat: Notify when a report generates an error.
  src/store/modules/ADempiere/reportManager.js
Labels: bug

#87 Suppurt print format
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/reportManager.js
  src/store/modules/tagsView.js
Labels: enhancement

#90 Support Print Window
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/reportManager.js
  src/store/modules/tagsView.js
  src/utils/ADempiere/dictionary/window.js
Labels: enhancement

#91 Run from Window
  docs/.vuepress/public/images/use-cases/report/run/open-windows.gif
  docs/es/guide/use-cases/reports.md
  docs/guide/use-cases/reports.md
Labels: documentation

#92 feat: Displayed report associated in button field.
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/utils/ADempiere/dictionary/window.js
  src/views/ADempiere/Window/MultiTabWindow.vue
Labels: enhancement

#93 Add isLoading Data Table
  src/api/ADempiere/browser.js
  src/lang/ADempiere/en/actionMenu.js
  src/lang/ADempiere/es/actionMenu.js
  src/store/modules/ADempiere/browserManager.js
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/dictionary/browser.js
  src/views/ADempiere/Browser/index.vue
Labels: bug

#100 feat: Add open Smart Browser associated.
  src/api/ADempiere/browser.js
  src/lang/ADempiere/en/actionMenu.js
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/en/route.js
  src/lang/ADempiere/en/smartBrowser.js
  src/lang/ADempiere/es/actionMenu.js
  src/lang/ADempiere/es/index.js
  src/lang/ADempiere/es/route.js
  src/lang/ADempiere/es/smartBrowser.js
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/ADempiere/browserManager.js
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/fieldValue.js
  src/utils/ADempiere/dictionary/window.js
  src/views/ADempiere/Browser/index.vue
Labels: enhancement

#104 feat: Add button process.
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/apiConverts/field.js
  src/utils/ADempiere/coreUtils.js
  src/utils/ADempiere/dictionary/window.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/references.js
  src/views/ADempiere/Window/index.vue
Labels: enhancement

#102 Support Delete Record in Smart Browser
  src/api/ADempiere/common/persistence.js
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/utils/ADempiere/dictionary/browser.js
Labels: enhancement
