Repository solop-develop/frontend-core, pull requests merged in 2023-06, with the labels that each got.

#1021 feat: Support to Service Process (Payment Allocation)
  src/api/ADempiere/form/VAllocation.js
  src/store/modules/ADempiere/fieldValue.js
  src/store/modules/ADempiere/form/VAllocation.js
  src/store/modules/ADempiere/form/VBankStatementMatch.js
Labels: enhancement, (FRM) Form

#1022 fix: Fixed header with Issue form
  src/layout/index.vue
Labels: bug, (FRM) Form, (UX) User Experience

#1028 Fix: No SDN Name to define SI Client when creating new SDN
  src/store/modules/ADempiere/windowManager.js
Labels: bug, (WIN) Windows, (REC) Records

#1024 fix: Add Location Address From
  src/store/modules/ADempiere/dictionary/process/actions.js
  src/store/modules/ADempiere/panel/actions.js
Labels: (WIN) Windows, (REC) Records, (FRM) Form

#1035 Fix: Get Context Attributes listWithout SDN Name to define SI Client when creating new SDN
  src/store/modules/ADempiere/windowManager.js
  src/utils/ADempiere/dictionary/window.js
Labels: bug, (WIN) Windows, (REC) Records

#1040 fix: Callout document type.
  src/store/modules/ADempiere/calloutManager.js
Labels: bug, (WIN) Windows

#1041 feat: Update nginx docker image.
  .github/workflows/publish.yml
  build/production-alpine.Dockerfile
  build/production.Dockerfile
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery

#1042 Increase Limit Record Rows by List
  src/api/ADempiere/form/timeControl.js
  src/api/ADempiere/window.js
  src/utils/ADempiere/references.js
Labels: enhancement, (REC) Records, (ULP) UI Lookups, (UX) User Experience

#1045 Get Chart Component to rendedr from chart type
  src/utils/ADempiere/dictionary/dashboard.js
Labels: bug, dashboard

#1050 feat: Add `BETWEEN` operator when is `Date` or `DateTime` field.
  src/utils/ADempiere/dataUtils.js
Labels: enhancement, (WIN) Windows, (REC) Records

#1058 fix: Refresh record after run process always.
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/dictionary/window.js
Labels: bug, (WFL) Workflows, (WIN) Windows

#1053 Fix: Table Search Fields
  src/api/ADempiere/field/search.js
Labels: enhancement, (ULP) UI Lookups

#1062 Fix isKey Field to send as selection value in processing
  src/store/modules/ADempiere/browserManager.js
Labels: bug, (SB) Smart Browser, (REC) Records

#1065 feat: Add operators to smart browsers
  src/api/ADempiere/browser.js
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
  src/layout/components/Navbar.vue
  src/store/modules/ADempiere/dictionary/browser/getters.js
  src/utils/ADempiere/dataUtils.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: (SB) Smart Browser, (REC) Records, (ULP) UI Lookups, (UX) User Experience

#1067 Fix: Process Activity
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
  src/views/ADempiere/ProcessActivity/processActivity.js
Labels: enhancement, (PRC) Processes

#1068 add Icon the Details
  src/icons/svg/details.svg
Labels: enhancement, (PRC) Processes

#1071 Add Copy Output
  src/lang/ADempiere/en/page/processActivity.js
  src/lang/ADempiere/es/page/processActivity.js
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
  src/views/ADempiere/ProcessActivity/processActivity.js
Labels: enhancement, (PRC) Processes

#1077 Adding Quick Options to the Process
  src/views/ADempiere/Process/index.vue
Labels: enhancement, (PRC) Processes, (UX) User Experience

#1079 Notification Alignment
  src/utils/ADempiere/notification.js
Labels: bug, (PRC) Processes

#1093 fix: Generate report on window.
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: bug, (RPT) Reports, (WIN) Windows

#1096 feat: `Document Action` panel on Tab Process
  src/lang/ADempiere/en/actionMenu.js
  src/lang/ADempiere/es/actionMenu.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/processManager.js
  src/utils/ADempiere/dictionary/window.js
  src/utils/ADempiere/dictionary/workflow.js
Labels: enhancement, (WFL) Workflows, (WIN) Windows

#1097 Add Default Opened Tab in Store
  src/store/modules/ADempiere/containerInfo/index.js
Labels: bug, (WIN) Windows, (REC) Records, (FRM) Form

#1120 feat: Add Copy record on window.
  src/lang/ADempiere/en/window.js
  src/lang/ADempiere/es/window.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/constants/systemColumns.js
  src/utils/ADempiere/dictionary/window.js
Labels: enhancement, (WIN) Windows, (REC) Records, (UX) User Experience

#1117 Feat: Add Export Record
  src/api/ADempiere/form/accouting.js
Labels: enhancement, (WIN) Windows, (REC) Records

#1124 Fix: Add Re-Run
  src/lang/ADempiere/en/page/processActivity.js
  src/lang/ADempiere/es/page/processActivity.js
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
Labels: (FRM) Form, (UX) User Experience
