Repository solop-develop/frontend-core, pull requests merged in 2023-03, with the labels that each got.

#898 feat: Add report type on menu to generate report.
  src/utils/ADempiere/dictionary/report.js
  src/utils/ADempiere/resource.js
  src/utils/ADempiere/valueUtils.js
  src/views/ADempiere/Report/mixinReport.js
Labels: enhancement, (RPT) Reports

#900 fix: Report set default values on report configuration panel.
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewer/index.vue
Labels: bug, (RPT) Reports

#901 perf: Remove old process run code.
  src/store/modules/ADempiere/form/workflowActivity.js
  src/store/modules/ADempiere/processControl.js
Labels: enhancement, (CIO) Code Improvement or Optimization

#908 fix: Run Smart Browser process with selection.
  src/store/modules/ADempiere/browserManager.js
  src/store/modules/ADempiere/processManager.js
Labels: bug, (PRC) Processes, (SB) Smart Browser, (REC) Records

#910 fix: Smart Browser with record id.
  src/store/modules/ADempiere/browserManager.js
  src/store/modules/ADempiere/processManager.js
  src/utils/ADempiere/constants/systemColumns.js
  src/utils/ADempiere/dictionary/window.js
Labels: bug, (PRC) Processes, (SB) Smart Browser, (WIN) Windows, (REC) Records

#915 fix: List lookups with old context.
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/fieldValue.js
  src/store/modules/ADempiere/panel/actions.js
  src/utils/ADempiere/contextUtils.js
  src/utils/ADempiere/dictionary/window.js
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#922 fix: Country without region displayed region field if is capture sequ…
  src/store/modules/ADempiere/field/locationAddress.js
  src/store/modules/ADempiere/panel/actions.js
Labels: bug, (ULP) UI Lookups

#932 fix: Logout send JWT authtorization.
  src/api/user.js
  src/store/modules/user.js
Labels: bug, (SE) Security

#936 fix: Session UUID with change role / change organization.
  src/api/role.js
  src/store/modules/user.js
Labels: bug, (SE) Security

#947 Add service Set Session Attribute
  src/api/user.js
  src/store/modules/app.js
  src/store/modules/user.js
Labels: enhancement, (SE) Security, (CIO) Code Improvement or Optimization

#949 Fixed generate the page token
  src/utils/ADempiere/dataUtils.js
Labels: bug, (WIN) Windows
