Repository solop-develop/frontend-core, pull requests merged in 2024-11, with the labels that each got.

#2883 Fix: Keep Record In Window
  src/store/modules/ADempiere/windowManager.js
Labels: bug, (WIN) Windows, (REC) Records

#2917 Fix: Size Table Windown
  src/components/ADempiere/DataTable/Windows/index.vue
  src/components/ADempiere/TabManager/TabPanel/modeDesktop.vue
  src/utils/ADempiere/componentUtils.js
Labels: (WIN) Windows, (UX) User Experience

#2918 Fix: Name Report Engine
  src/views/ADempiere/ReportViewerEngine/index.vue
Labels: (RPT) Reports

#2919 Fix: Size Column Table Window
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#2920 Fix: Add get Unit Of Measure definition.
  src/api/ADempiere/system-core.js
  src/components/ADempiere/FieldDefinition/FieldNumber.vue
  src/store/modules/user.js
  src/utils/ADempiere/constants/systemColumns.js
  src/utils/ADempiere/references.js
Labels: bug, (ULP) UI Lookups

#2926 Fix: Accounting Entry Line
  src/components/ADempiere/Form/AcctViewer/QueryCriteria/index.vue
  src/components/ADempiere/Form/AcctViewer/TableRecords/index.vue
  src/lang/ADempiere/en/form/accountingViewer.js
  src/lang/ADempiere/es/form/accountingViewer.js
Labels: (WIN) Windows, (FRM) Form, (UX) User Experience

#2929 fix: Report Engine duplicated zoom.
  src/components/ADempiere/Report/Data/DataCells.vue
  src/utils/ADempiere/constants/report.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: bug, (RPT) Reports, (REC) Records, (UX) User Experience

#2930 Fix: Zoom In Report Engine
  src/components/ADempiere/Report/Data/DataCells.vue
  src/store/modules/ADempiere/zoomManager.js
Labels: bug, (RPT) Reports, (REC) Records

#2931 Fix: Summary Cash Flow Statement
  src/api/ADempiere/form/VPOS/index.js
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashClosing/panel.vue
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2934 Preset Use of Funds
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/panel.vue
Labels: enhancement, (POS) Point Of Sales

#2947 Fix: Tender Type
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashClosing/panel.vue
  src/store/modules/ADempiere/form/VPOS/options.js
Labels: bug, (POS) Point Of Sales

#2951 Fix bug in Delete Option
  src/components/ADempiere/DataTable/Components/CellDisplayInfo.vue
Labels: bug, (WIN) Windows, (REC) Records

#2942 Fix: Collapsa Pos
  src/layout/components/Navbar.vue
  src/layout/components/ProfilePreview.vue
  src/layout/components/Sidebar/Logo.vue
  src/store/modules/user.js
  src/utils/ADempiere/resource.js
  src/utils/set-value-page.js
  src/views/profile/components/UserCard.vue
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2949 Fix: Mnemonic Command
  src/components/ADempiere/TabManager/index.vue
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
Labels: bug, (WIN) Windows, (UX) User Experience

#2956 Fix: Sum Report Engine
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2960 Fix: Amount In Accounting
  src/components/ADempiere/Form/AcctViewer/TableRecords/index.vue
  src/components/ADempiere/Form/AcctViewer/TableRecords/sourceColumns.vue
Labels: bug, (WIN) Windows, (FRM) Form

#2958 Clear Data when Withdrawing or Opening
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/fields/cashBank.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/index.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/panel.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/fields/cashBank.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/panel.vue
  src/store/modules/ADempiere/form/VPOS/options/cashManagement/cashOpen.js
  src/store/modules/ADempiere/form/VPOS/options/cashManagement/cashwithdrawal.js
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2955 Fix: Buttons the Delete
  src/utils/ADempiere/dictionary/window/index.js
Labels: bug, (REC) Records, (SE) Security

#2962 Fix: Align Number In Report Engine
  src/utils/ADempiere/references.js
Labels: (RPT) Reports, (ULP) UI Lookups, (UX) User Experience

#2965 Fix: User Image
  src/store/modules/user.js
Labels: bug, Attachment

#2973 Fix: Cash Open and Cash Withdrawal
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/fields/currency.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/panel.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/fields/currency.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/panel.vue
Labels: bug, (POS) Point Of Sales

#2975 Fix: Change Positions Image
  src/views/login/index.vue
Labels: enhancement, (UX) User Experience

#2976 feat: Add `DisplayColumn` value on `Record_ID` column.
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/utils/ADempiere/constants/systemColumns.js
  src/utils/ADempiere/valueFormat.js
Labels: enhancement, (WIN) Windows, (REC) Records, (ULP) UI Lookups

#2977 fix: Report with `AD_Table_ID` and `Record_ID` context.
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/store/modules/ADempiere/dictionary/process/getters.js
  src/store/modules/ADempiere/dictionary/report/getters.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/constants/systemColumns.js
Labels: bug, (PRC) Processes, (RPT) Reports, (WIN) Windows, (REC) Records

#2971 Fix: Line Currency does not Respect head Currency
  src/components/ADempiere/FieldDefinition/FieldNumber.vue
Labels: bug, (WIN) Windows, (REC) Records

#2981 Fix: Display Password in Table
  src/components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  src/components/ADempiere/FieldDefinition/FieldText.vue
Labels: bug, (ULP) UI Lookups

#2982 fix: Set tab context on process.
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: (PRC) Processes, (RPT) Reports, (WIN) Windows

#2983 fix: Zero context values with decimals.
  src/utils/ADempiere/contextUtils/evaluator.js
Labels: bug, (ULP) UI Lookups

#2985 Fix: Fixed Width in Column Name
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience

#2984 The currency should display the code instead of a number.
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/editLine/fieldAmount.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/panel.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashWithdrawal/panel.vue
Labels: bug, (POS) Point Of Sales

#2987 Fix: Receiving Order Display Logic
  src/utils/ADempiere/contextUtils/evaluator.js
Labels: bug, (ULP) UI Lookups

#2946 Fix: Save When Editing Mnemonic Command
  src/components/ADempiere/TabManager/index.vue
Labels: (UX) User Experience

#2990 Fix: Incorrect window display comparing notebook with desktop terminal
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/components/ADempiere/FieldDefinition/index.vue
  src/components/ADempiere/TabManager/index.vue
Labels: bug, (UX) User Experience

#2991 fix: Report empty with regenerate.
  src/layout/components/TagsView/index.vue
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/form/VPOS/options.js
  src/store/modules/ADempiere/pointOfSales/order/actions.js
  src/store/modules/ADempiere/report/reportRun.js
  src/store/modules/ADempiere/reportManager.js
  src/store/modules/tagsView.js
  src/utils/ADempiere/constants/report.js
  src/utils/ADempiere/dictionary/process.js
  src/utils/ADempiere/dictionary/report/actionsMenu.ts
  src/utils/ADempiere/dictionary/report/index.js
  src/views/ADempiere/ProcessActivity/processActivity.js
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/index.vue
Labels: bug, (RPT) Reports

#2993 fix: Export records on Smart Browse.
  src/lang/ADempiere/en/smartBrowser.js
  src/lang/ADempiere/es/smartBrowser.js
  src/utils/ADempiere/dictionary/browser/actionsMenu.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/exportUtil.js
Labels: bug, (SB) Smart Browser, (REC) Records

#2995 feat: Add preview on image field.
  src/components/ADempiere/FieldDefinition/FieldImage.vue
Labels: enhancement, (ULP) UI Lookups, Attachment

#2989 Fix: Date in English format in Major accountant despite being in Spanish language
  src/components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  src/components/ADempiere/Report/Data/DataCells.vue
  src/utils/ADempiere/valueFormat.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#2996 Fix: Record Id Not Defined
  src/components/ADempiere/TabManager/convenienceButtons/documentAction.vue
Labels: bug, (WFL) Workflows, (REC) Records

#2999 Fix: Sum In Payment Assignment
  src/components/ADempiere/FormDefinition/VAllocation/components/Payments.vue
Labels: bug, (FRM) Form
