Repository solop-develop/frontend-core, pull requests merged in 2024-07, with the labels that each got.

#2404 feat: Table Name on field search display type.
  src/api/ADempiere/dictionary/field.ts
  src/api/ADempiere/field/search/index.js
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/index.vue
  src/store/modules/ADempiere/field/search/generalSearch.js
  src/utils/ADempiere/dictionary/browser/index.js
  src/utils/ADempiere/dictionary/field/search/index.ts
  src/utils/ADempiere/dictionary/process.js
  src/utils/ADempiere/dictionary/window/index.js
Labels: enhancement, (ULP) UI Lookups

#2405 Fix: Related records from child tabs
  src/components/ADempiere/PanelInfo/index.vue
Labels: bug, (REC) Records

#2391 Fix: Record Prices At 0
  src/components/ADempiere/FieldDefinition/mixin/mixinField.js
  src/store/modules/ADempiere/persistence.js
Labels: bug, (WIN) Windows, (REC) Records

#2412 fix: Set Business Partner on search field.
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/useBusinessPartner.js
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/PanelForm/useInvoce.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/useOrder.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/usePayment.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/useProduct.js
  src/components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (ULP) UI Lookups

#2420 Feature/report engine change parameters
  src/components/ADempiere/FieldDefinition/FieldOptions/ComparisonOperator.vue
  src/lang/ADempiere/en/operators.ts
  src/lang/ADempiere/es/operators.ts
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports

#2422 fix: Evaluator with empty value on context.
  src/utils/ADempiere/contextUtils/evaluator.js
Labels: bug

#2423 Bugfix/fix support print format
  src/api/ADempiere/reportManagement/index.ts
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2392 Support Multi Tenants
  src/api/ADempiere/dictionary/window.ts
  src/api/ADempiere/security/index.ts
  src/components/ADempiere/PanelInfo/index.vue
  src/components/ADempiere/TabManager/index.vue
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/panel/actions.js
  src/store/modules/ADempiere/windowManager.js
  src/utils/ADempiere/dictionary/browser/templateBrowser.js
  src/utils/ADempiere/dictionary/window/index.js
  src/utils/ADempiere/dictionary/window/templatesWindow.js
  src/views/ADempiere/Browser/index.vue
  src/views/ADempiere/Window/index.vue
Labels: (MEN) Menues, (SB) Smart Browser, (WIN) Windows, Attachment

#2430 Fix: Navigate With Changes
  src/components/ADempiere/DataTable/Components/ChangeRecord.vue
Labels: bug, (WIN) Windows, (REC) Records

#2437 fix: Save new with zero value.
  src/api/ADempiere/userInterface/entities.ts
  src/store/modules/ADempiere/persistence.js
Labels: bug, (WIN) Windows, (REC) Records

#2439 fix: Callout cast string to date.
  src/store/modules/ADempiere/calloutManager.js
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#2432 fix: Advanced Project Search
  src/api/ADempiere/field/search/business-partner.ts
  src/api/ADempiere/field/search/index.js
  src/api/ADempiere/field/search/invoice.ts
  src/api/ADempiere/field/search/order.ts
  src/api/ADempiere/field/search/payment.ts
  src/api/ADempiere/field/search/product.ts
  src/api/ADempiere/userInterface/lookups.ts
  src/components/ADempiere/FieldDefinition/FieldSelect/index.vue
  src/components/ADempiere/TabManager/AdvancedTabQuery.vue
  src/store/modules/ADempiere/field/search/businessPartnerSearch.js
  src/store/modules/ADempiere/field/search/generalSearch.js
  src/store/modules/ADempiere/field/search/invoiceFieldSearch.js
  src/store/modules/ADempiere/field/search/orderFieldSearch.js
  src/store/modules/ADempiere/field/search/paymentFieldSearch.js
  src/store/modules/ADempiere/field/search/productFieldSearch.js
  src/store/modules/ADempiere/lookupManager.js
Labels: enhancement, (WIN) Windows, (REC) Records

#2442 fix: Number field range To.
  src/lang/ADempiere/en/field/index.js
  src/lang/ADempiere/es/field/index.js
  src/store/modules/ADempiere/calloutManager.js
  src/store/modules/ADempiere/dictionary/browser/getters.js
  src/store/modules/ADempiere/dictionary/process/getters.js
  src/store/modules/ADempiere/dictionary/report/getters.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/references.js
Labels: bug, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (ULP) UI Lookups

#2445 fix: #2431 Document Type validation on Process associated smart browser.
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/panel/getters.js
  src/utils/ADempiere/contextUtils/contextField.js
  src/utils/ADempiere/contextUtils/index.js
Labels: bug, (PRC) Processes, (SB) Smart Browser, (REC) Records

#2446 feat: Update `NGNX` from 1.25.3 to 1.27.0.
  build/production-alpine.Dockerfile
  build/production.Dockerfile
Labels: (CI/CD) Continuous Integration/Continous Delivery, (ULB) Update Library, (CIO) Code Improvement or Optimization

#2447 fix: Edit zero value on record.
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
  src/store/modules/ADempiere/persistence.js
Labels: bug, (WIN) Windows, (REC) Records

#2450 feat: Get menu multitenant.
  src/api/ADempiere/dictionary/form.js
  src/api/ADempiere/dictionary/process.js
  src/api/ADempiere/dictionary/smart-browser.js
  src/api/ADempiere/dictionary/window.ts
  src/api/ADempiere/security/index.ts
  src/router/modules/ADempiere/menu.js
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/dictionary/process/actions.js
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/formDefinition.js
Labels: (MEN) Menues

#2452 Fix: Style Table Report Engine
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2454 Add Summary Report Engine
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports, Attachment

#2455 Fix: Modal Report Enginer
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/views/ADempiere/ReportViewerEngine/infoReport.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2457 fix: Run business process.
  src/api/ADempiere/business-data/runBusinessProcess.ts
  src/api/ADempiere/process.js
  src/components/ADempiere/Process/ExportDictionaryDefinition.vue
  src/store/modules/ADempiere/processManager.js
  src/store/modules/ADempiere/system.js
  src/views/ADempiere/Browser/index.vue
Labels: (PRC) Processes, (RPT) Reports

#2448 Fix: Process Payment Assignment
  src/components/ADempiere/FieldDefinition/FieldSelect/emptyOptionSelect.vue
  src/components/ADempiere/FormDefinition/VAllocation/ProcessFooter/organizationTransactionField.vue
  src/components/ADempiere/FormDefinition/VAllocation/SearchCriteria/organizationField.vue
  src/components/ADempiere/FormDefinition/VAllocation/components/Payments.vue
  src/components/ADempiere/FormDefinition/VAllocation/index.vue
  src/store/modules/ADempiere/form/VAllocation.js
Labels: bug, (FRM) Form

#2440 Fix Error in the Field: Search > Invoice Sale/Purchase
  src/api/ADempiere/dictionary/field.ts
  src/api/ADempiere/field/search/business-partner.ts
  src/api/ADempiere/field/search/index.js
  src/api/ADempiere/field/search/invoice.ts
  src/api/ADempiere/field/search/order.ts
  src/api/ADempiere/field/search/product.ts
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/PanelForm/useInvoce.js
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/useOrder.js
  src/store/modules/ADempiere/field/search/businessPartnerSearch.js
  src/store/modules/ADempiere/field/search/generalSearch.js
  src/store/modules/ADempiere/field/search/invoiceFieldSearch.js
  src/store/modules/ADempiere/field/search/orderFieldSearch.js
  src/store/modules/ADempiere/field/search/paymentFieldSearch.js
  src/store/modules/ADempiere/field/search/productFieldSearch.js
Labels: bug, (ULP) UI Lookups

#2461 feat: `YesNo` field as `List` on reports.
  src/components/ADempiere/FieldDefinition/FieldYesNo/index.vue
Labels: enhancement, (RPT) Reports, (ULP) UI Lookups

#2463 fix: Change report output.
  src/api/ADempiere/logs/process.ts
  src/api/ADempiere/reportManagement/index.ts
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/processManager.js
  src/store/modules/ADempiere/reportManager.js
  src/utils/ADempiere/apiConverts/process.js
  src/utils/ADempiere/apiConverts/report.js
  src/utils/ADempiere/dictionary/report/actionsMenu.ts
  src/views/ADempiere/ReportViewer/index.vue
  tests/unit/utils/ADempiere/apiConverts/report.spec.js
Labels: bug, (RPT) Reports

#2464 feat: `UUID` Workflow value by server.
  src/store/modules/ADempiere/workflowDefinition.js
Labels: enhancement, (WFL) Workflows

#2466 perf: Remove unused and dupicated definitions.
  src/api/ADempiere/business-data/entities.ts
  src/api/ADempiere/common/index.ts
  src/api/ADempiere/form/VPOS/index.js
  src/api/ADempiere/form/point-of-sales.js
  src/api/ADempiere/process.js
  src/api/ADempiere/security/index.ts
  src/api/ADempiere/system-core.js
  src/components/ADempiere/Form/VPOS/Collection/typeCollection.vue
  src/store/modules/ADempiere/form/VPOS/collection.js
  src/store/modules/ADempiere/form/VPOS/lines.js
  src/store/modules/ADempiere/pointOfSales/orderLine/actions.js
  src/store/modules/ADempiere/pointOfSales/payments/actions.js
  src/store/modules/user.js
  tests/unit/utils/ADempiere/apiConverts/objects/converted/process.json
  tests/unit/utils/ADempiere/apiConverts/objects/converted/processLog.json
  tests/unit/utils/ADempiere/apiConverts/objects/converted/processLogWithReport.json
  tests/unit/utils/ADempiere/apiConverts/objects/converted/processWithUndefined.json
  tests/unit/utils/ADempiere/apiConverts/objects/fromApi/process.json
  tests/unit/utils/ADempiere/apiConverts/objects/fromApi/processLog.json
  tests/unit/utils/ADempiere/apiConverts/objects/fromApi/processLogWithReport.json
  tests/unit/utils/ADempiere/apiConverts/objects/fromApi/processWithUndefined.json
  tests/unit/utils/ADempiere/apiConverts/process.spec.js
Labels: enhancement, (CIO) Code Improvement or Optimization

#2467 perf: Remove unused request to POS.
  src/api/ADempiere/form/VPOS/customer.js
  src/api/ADempiere/form/point-of-sales.js
  src/api/ADempiere/system-core.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/index.vue
  src/store/modules/ADempiere/form/VPOS/customer.js
Labels: enhancement, (CIO) Code Improvement or Optimization

#2468 fix: POS List Bank Accounts with mandatory Bank identifier.
  src/api/ADempiere/form/VPOS/banks.js
  src/api/ADempiere/form/VPOS/customer.js
  src/api/ADempiere/form/VPOS/index.js
  src/components/ADempiere/Form/VPOS2/Collection/Refund/Field/banksAccounts.vue
  src/store/modules/ADempiere/form/VPOS/fieldsCollections.js
Labels: bug, (FRM) Form, (POS) Point Of Sales, (CIO) Code Improvement or Optimization

#2469 fix: List Products with mandatory Order identifier.
  src/api/ADempiere/form/expres-movement.js
  src/api/ADempiere/form/express-receipt.js
  src/api/ADempiere/form/express-shipment.js
  src/components/ADempiere/FormDefinition/ExpressMovement/index.vue
  src/components/ADempiere/FormDefinition/ExpressReceipt/index.vue
  src/components/ADempiere/FormDefinition/ExpressShipment/index.vue
  src/lang/ADempiere/es/form/index.js
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/ADempiere/form/expressMovement.js
  src/store/modules/ADempiere/form/expressReceipt.js
  src/store/modules/ADempiere/form/expressShipment.js
Labels: bug, (FRM) Form, (CIO) Code Improvement or Optimization

#2465 Fix: Column Widths Report Enginer
  src/lang/ADempiere/en/component/attachment.js
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/component/attachment.js
  src/lang/ADempiere/es/report.js
  src/utils/ADempiere/references.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/dialogShare.vue
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports

#2471 Fix: Refresh Table
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports, (CIO) Code Improvement or Optimization

#2473 fix: List `IsActive` records on search field.
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/index.vue
  src/lang/ADempiere/en/field/index.js
  src/lang/ADempiere/es/field/index.js
  src/styles/ADempiere/table.scss
  src/utils/ADempiere/dictionary/field/search/index.ts
Labels: bug, (REC) Records, (SE) Security, (ULP) UI Lookups

#2478 fix: SB `Create From Invoice` infinite loop.
  src/components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  src/utils/ADempiere/dictionary/browser/index.js
Labels: bug, (SB) Smart Browser, (SE) Security, (UX) User Experience

#2480 Fix: Dialog functionality
  src/api/ADempiere/reportManagement/index.ts
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/store/modules/ADempiere/reportManager.js
  src/utils/ADempiere/notification.js
  src/views/ADempiere/ReportViewerEngine/dialog/contactSend.vue
  src/views/ADempiere/ReportViewerEngine/dialog/copyLink.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/typeNotify.vue
Labels: enhancement, (RPT) Reports

#2481 Fix: Copy Link Report Enginer
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/utils/ADempiere/notification.js
  src/views/ADempiere/ReportViewerEngine/dialog/copyLink.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2486 Set XLSX format
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2482 Fix: Type Notify
  src/views/ADempiere/ReportViewerEngine/dialog/typeNotify.vue
Labels: bug, (RPT) Reports

#2483 FIx: Generate report with the esl GetView service
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
Labels: bug, (RPT) Reports

#2485 send the parameters correctly
  src/utils/ADempiere/valueUtils.js
Labels: enhancement, (RPT) Reports

#2484 FIx: When the Print Format, Page or view is changed, the original set…
  src/utils/ADempiere/dictionary/report.js
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: bug, (RPT) Reports, (UX) User Experience

#2487 executing a request every time the link duration is selected
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
Labels: enhancement, (RPT) Reports

#2489 Fix: Aling Vertical
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
Labels: bug, (RPT) Reports

#2488 Fix: Show Popover
  src/views/ADempiere/Report/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: bug, (RPT) Reports

#2491 fix: Load menu without child nodes.
  src/router/modules/ADempiere/menu.js
Labels: bug, (MEN) Menues, (SE) Security

#2490 Fix: Refresh button report enginer
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/refreshButton.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports, (UX) User Experience

#2492 Adding Download, Send and Share Functionality
  src/api/ADempiere/reportManagement/index.ts
  src/lang/ADempiere/es/report.js
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/contactSend.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2493 Fix: Color in popover
  src/views/ADempiere/ReportViewerEngine/infoReport.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports, (UX) User Experience

#2494 Fix: Show MarkDown
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports, (UX) User Experience

#2497 Fix: Responsive Search Criteria
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/refreshButton.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports, (UX) User Experience

#2496 Fix: Default xlsx
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2498 Fix: No Hide Column Parent
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2499 Fix: Show dialog error
  src/api/ADempiere/reportManagement/index.ts
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2500 Fix: Traslate Dialog
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2504 Fix: Excel fila traslate
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
Labels: bug, (RPT) Reports, (TRL) Translation

#2503 Fix : Traslate subjet
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports, (TRL) Translation

#2505 Fix: Popover
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2506 Buugfix/reload report
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/refreshButton.vue
Labels: enhancement, (RPT) Reports

#2508 Mailing Template
  src/store/modules/ADempiere/mailTemplate.js
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
Labels: (RPT) Reports

#2509 Fix: Aling criteria
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/printFormatReport.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/refreshButton.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports

#2512 Fix: Preview link
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/index.vue
Labels: enhancement, (RPT) Reports

#2514 Fix: Hidden preview
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: (RPT) Reports

#2516 Fix: Params in export
  src/api/ADempiere/reportManagement/index.ts
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2517 Fix: Remplace url in body
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2525 Fix: Services and Style
  src/api/ADempiere/reportManagement/index.ts
  src/views/ADempiere/ReportViewerEngine/dialog/contactSend.vue
  src/views/ADempiere/ReportViewerEngine/dialog/typeNotify.vue
Labels: (RPT) Reports

#2529 Fix: Remplace url
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports

#2533 Fix: Popover data report enginer
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2534 Bugfix/fix field image delete
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/FileShare.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/fileInfo.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
  src/components/ADempiere/TabManager/index.vue
Labels: (RPT) Reports, Attachment

#2535 Fix: Field Image
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/FileShare.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
Labels: enhancement, (RPT) Reports, (ULP) UI Lookups, Attachment

#2536 Fix: Style Menu
  src/styles/sidebar.scss
  src/utils/ADempiere/dictionary/menu.js
Labels: enhancement, (MEN) Menues

#2537 feat: Enable `Export Dictionary Definition` form only `System` role.
  src/components/ADempiere/Process/ExportDictionaryDefinition.vue
  src/router/modules/ADempiere/staticRoutes.js
  src/utils/ADempiere/dictionary/process/exportDictionaryDefinition.ts
Labels: enhancement, (PRC) Processes, (MEN) Menues

#2538 Fix: Clean data when closing report
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: bug, (RPT) Reports

#2539 Fix: No clear link
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: bug, (RPT) Reports

#2543 Fix: Style dialog report enginer
  src/views/ADempiere/ReportViewerEngine/dialog/contactSend.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/typeNotify.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports

#2547 Fix: Hidden title children
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports

#2541 Fix: Show popover click
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports

#2544 Fix: Validate lookup report enginer
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports

#2548 Fix: Change logic sumary
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
  src/views/ADempiere/ReportViewerEngine/searchCriteria/reportSumary.vue
Labels: enhancement, (RPT) Reports

#2549 Support Attachment Resource
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/FileShare.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/fileInfo.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
  src/components/ADempiere/TabManager/index.vue
  src/store/modules/ADempiere/attachmentManager.js
  src/utils/ADempiere/dictionary/window/index.js
  src/utils/ADempiere/resource.js
Labels: enhancement, (WIN) Windows, Attachment
