Repository solop-develop/frontend-core, pull requests merged in 2024-02, with the labels that each got.

#1897 fix: Create Address Location.
  src/api/ADempiere/field/location-address.ts
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Address.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Address2.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Address3.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Address4.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/City.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/CityLabel.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Country.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/PosalCodeAdditional.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/PostalCode.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/Fields/Regions.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/address1Field.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/address2Field.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/address3Field.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/address4Field.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/citiesListField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/cityNameField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/countriesListField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/index.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/postalCodeAdditionalField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/postalCodeField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/regionsListField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm2.vue
  src/store/modules/ADempiere/field/locations.js
  src/store/modules/ADempiere/form/VPOS/customer.js
  src/utils/ADempiere/dictionary/field/locationAddress.js
  src/utils/ADempiere/valueUtils.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#1898 Fix: Change Style Chart Gauje
  package.json
  src/components/ADempiere/Dashboard/charts/AreaChart.vue
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/CustomerChart.vue
  src/components/ADempiere/Dashboard/charts/Gauge.vue
  src/components/ADempiere/Dashboard/charts/LineChart.vue
  src/components/ADempiere/Dashboard/charts/PieChart.vue
  src/components/ADempiere/Dashboard/charts/RaddarChart.vue
  src/components/ADempiere/Dashboard/charts/Scatter.vue
  src/components/ADempiere/Dashboard/charts/WaterfallChart.vue
  src/components/ADempiere/Dashboard/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
  src/components/ADempiere/PageStyleSettings/Settings.vue
  src/components/Charts/MixChart.vue
  src/store/modules/ADempiere/dashboard.js
  src/views/dashboard/admin/index.vue
  yarn.lock
Labels: bug, dashboard

#1901 fix: Gauge chart with multiple values.
  src/components/ADempiere/Dashboard/charts/BarChart.vue
  src/components/ADempiere/Dashboard/charts/Gauge.vue
Labels: bug, dashboard, (UX) User Experience

#1902 Fix: Open ID end-point
  src/api/ADempiere/security/index.ts
Labels: bug, (SE) Security

#1899 Feat: Presigned Url
  src/api/ADempiere/file-management/resource-reference.ts
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResourceOld.vue
  src/utils/ADempiere/request.js
Labels: enhancement, (WIN) Windows

#1903 fix: Cast correct parameter value by display type.
  src/store/modules/ADempiere/dictionary/process/getters.js
  src/store/modules/ADempiere/dictionary/report/getters.js
Labels: bug, (PRC) Processes, (RPT) Reports

#1907 fix: Lookups default value in table.
  src/components/ADempiere/FieldDefinition/FieldSelect.vue
  src/components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
  src/store/modules/ADempiere/defaultValueManager.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#1908 fix: Lookups list inactive records.
  src/api/ADempiere/field/search/index.ts
  src/api/ADempiere/userInterface/defaultValue.ts
  src/api/ADempiere/userInterface/lookups.ts
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  src/components/ADempiere/FieldDefinition/FieldSelect.vue
  src/store/modules/ADempiere/defaultValueManager.js
  src/store/modules/ADempiere/lookupManager.js
  src/utils/ADempiere/lookups.ts
Labels: bug, (REC) Records, (ULP) UI Lookups, (UX) User Experience

#1909 fix: SB Read only table when edit column.
  src/components/ADempiere/DataTable/Browser/index.vue
  src/components/ADempiere/FieldDefinition/index.vue
Labels: bug, (SB) Smart Browser, (ULP) UI Lookups, (UX) User Experience

#1911 fix: Field Date `formatView` is undefined.
  src/components/ADempiere/FieldDefinition/FieldDate.vue
  src/views/profile/components/RolesNavbar.vue
Labels: bug, (ULP) UI Lookups

#1913 fix: Smart Browse zoom window from query criteria field.
  src/components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
Labels: (SB) Smart Browser, (ULP) UI Lookups, (UX) User Experience

#1918 Fix:Changes Role and Organizations
  src/api/ADempiere/security/index.ts
  src/store/modules/user.js
  src/views/profile/components/RolesNavbar.vue
Labels: bug, (SE) Security

#1919 fix: Process view height style.
  src/views/ADempiere/Process/index.vue
  src/views/ADempiere/Report/index.vue
Labels: bug, (PRC) Processes, (RPT) Reports

#1926 fix: Search field change result with query criteria.
  src/api/ADempiere/field/search/index.ts
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  src/store/modules/ADempiere/field/search/generalSearch.js
Labels: bug, (ULP) UI Lookups

#1928 Support Clear Main path on startup with KeyCloak and error when chang…
  src/views/login/index.vue
  src/views/profile/components/RolesNavbar.vue
Labels: bug, (SE) Security

#1927 feat: Image s3 with minio
  config/default.json
  package.json
  src/api/ADempiere/file-management/resource-reference.ts
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/FileShare.vue
  src/lang/ADempiere/en/component/attachment.js
  src/lang/ADempiere/es/component/attachment.js
  yarn.lock
Labels: enhancement, (ULP) UI Lookups

#1929 fix: Docker image set api env.
  build/production-alpine.Dockerfile
  build/production.Dockerfile
  build/start.sh
  config/default.json
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery, (CIO) Code Improvement or Optimization

#1934 feat: Simplify issue form.
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/components/ADempiere/Form/Issues/ListIssues/items.vue
  src/components/ADempiere/Form/Issues/ListIssues/kanban.vue
  src/components/ADempiere/Form/Issues/component/Comment.vue
  src/components/ADempiere/Form/Issues/index.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssueFeed/issueCommentAdd.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssueFeed/issueCommentView.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssueFeed/issueLog.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssuesList/issuePreview.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssuesList/issueRow.vue
  src/components/ADempiere/FormDefinition/IssueManagement/index.vue
  src/components/ADempiere/FormDefinition/index.vue
  src/components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  src/components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  src/utils/ADempiere/dictionary/form/Issues.js
Labels: enhancement, (FRM) Form

#1935 feat: `Form Issues` and `Window Issues` same design.
  src/components/ADempiere/FieldDefinition/FieldSelect/emptyOptionSelect.vue
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/components/ADempiere/Form/Issues/ListIssues/kanban.vue
  src/components/ADempiere/Form/Issues/component/Comment.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssuesList/issuePreview.vue
  src/components/ADempiere/FormDefinition/IssueManagement/index.vue
  src/components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  src/components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: enhancement, (WIN) Windows, (FRM) Form, (UX) User Experience

#1939 feat: Start time traking.
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/components/ADempiere/Form/Issues/ListIssues/kanban.vue
  src/components/ADempiere/Form/Issues/component/Comment.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssueRecordTime/index.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssuesList/issueRow.vue
  src/components/ADempiere/FormDefinition/IssueManagement/index.vue
  src/components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  src/icons/svg/pause-circle.svg
  src/icons/svg/play-circle.svg
  src/icons/svg/stop-circle.svg
  src/lang/ADempiere/en/form/timeRecord.js
  src/lang/ADempiere/es/form/timeRecord.js
  src/styles/ADempiere/form.scss
Labels: enhancement, (FRM) Form

#1943 fix: #1942 Table quantity precision show
  src/components/ADempiere/Form/VPOS/ConfirmDelivery/index.vue
  src/utils/ADempiere/formatValue/numberFormat.js
  src/utils/ADempiere/valueFormat.js
Labels: bug, (REC) Records, (ULP) UI Lookups

#1944 Support Attachement and Image
  src/api/ADempiere/file-management/resource-reference.ts
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  src/components/ADempiere/PanelInfo/index.vue
  src/components/ADempiere/TabManager/index.vue
  src/store/modules/ADempiere/attachmentManager.js
  src/utils/ADempiere/dictionary/window.js
  src/utils/ADempiere/resource.js
Labels: enhancement, (WIN) Windows

#1947 Feat: Change SIze Panel Main
  src/components/ADempiere/Dashboard/charts/Gauge.vue
  src/components/ADempiere/Dashboard/charts/Portlet.vue
  src/components/ADempiere/Dashboard/docstatus/index.vue
  src/components/ADempiere/Dashboard/notices/index.vue
  src/components/ADempiere/Dashboard/notices/itemsNotices.vue
  src/components/ADempiere/Dashboard/panelGroupPie/index.vue
  src/components/ADempiere/Dashboard/panelGroupPortlet/index.vue
  src/components/ADempiere/Dashboard/recentItems/index.vue
  src/components/ADempiere/Dashboard/userfavorites/index.vue
  src/store/modules/settings.js
  src/views/dashboard/admin/components/PanelGroup.vue
  src/views/dashboard/admin/index.vue
  src/views/profile/components/RolesNavbar.vue
Labels: dashboard

#1952 Fix Translation of the "Views" menu
  src/lang/ADempiere/en/route.js
  src/lang/ADempiere/es/route.js
  src/router/modules/ADempiere/staticRoutes.js
Labels: bug, (MEN) Menues, (TRL) Translation

#1954 fix: Set `Product Attribute` on smart browse.
  src/components/ADempiere/FieldDefinition/FieldProductAttribute/useProductAttribute.js
  src/components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (SB) Smart Browser, (ULP) UI Lookups

#1955 Fix: Incorrect date format in SB
  src/utils/ADempiere/valueFormat.js
Labels: bug, (SB) Smart Browser

#1956 fix: `Business Partner` field with is sales transaction value.
  src/components/ADempiere/DataTable/Components/BatchEntry.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/QueryCriteria/customerVendorField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/QueryCriteria/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/useBusinessPartner.js
  src/components/ADempiere/PanelDefinition/TreePanel.vue
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/dictionary/process/actions.js
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/panel/actions.js
  src/store/modules/ADempiere/panel/getters.js
  src/store/modules/ADempiere/windowManager.js
  src/utils/ADempiere/contextUtils/contextField.js
  src/utils/ADempiere/contextUtils/index.js
  src/utils/ADempiere/dictionary/window.js
  src/utils/ADempiere/dictionaryUtils.js
  src/utils/ADempiere/lookupFactory.js
Labels: (MEN) Menues, (WIN) Windows, (ULP) UI Lookups
