Repository solop-develop/frontend-core, pull requests merged in 2024-08, with the labels that each got.

#2550 Change ID to UUID
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: (WIN) Windows, (ULP) UI Lookups, Attachment

#2552 Change ID to UUID in Client
  src/layout/components/Sidebar/Logo.vue
  src/utils/set-value-page.js
Labels: Attachment

#2559 Separate Table Panel from the Report
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
  src/views/ADempiere/ReportViewerEngine/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: enhancement, (RPT) Reports, (CIO) Code Improvement or Optimization

#2560 Fix: Whiten Search Criteria
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/tableRecords.vue
Labels: (ULP) UI Lookups, (UX) User Experience

#2564 Fix: Store Independent Report Engine
  src/store/modules/ADempiere/notificationManager.js
  src/store/modules/ADempiere/report/report.js
  src/store/modules/ADempiere/report/reportEnginer.js
Labels: (RPT) Reports, (CIO) Code Improvement or Optimization

#2562 Fix: Hide Second Level Titles
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2567 Fix: Heigth Organization Rules
  src/views/ADempiere/Summary/index.vue
Labels: bug, (MEN) Menues, (UX) User Experience

#2568 Display image in user window with different arrangement
  src/components/ADempiere/FieldDefinition/FieldImage.vue
Labels: (WIN) Windows, (REC) Records, Attachment

#2554 Validate Company to upload attachment
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: (WIN) Windows, (REC) Records, (SE) Security, Attachment

#2570 Fix: Change endpoint
  src/api/ADempiere/reportManagement/index.ts
Labels: enhancement, (RPT) Reports

#2573 fix: Menu freezes when searching.
  src/components/HeaderSearch/index.vue
Labels: bug, (MEN) Menues, (UX) User Experience

#2575 Fix: Context attributes in `Order` serach field
  src/store/modules/ADempiere/field/search/orderFieldSearch.js
Labels: bug, (ULP) UI Lookups

#2577 Fix: Html In Notices
  config/default.json
  src/api/ADempiere/form/notice.js
  src/components/ADempiere/Dashboard/notices/index.vue
  src/components/ADempiere/Dashboard/notices/itemsNotices.vue
  src/icons/svg/read.svg
  src/lang/ADempiere/en/window.js
  src/lang/ADempiere/es/window.js
  src/store/modules/ADempiere/form/notices.js
Labels: enhancement, dashboard, (UX) User Experience

#2584 fix: Accouting Viewer filter with `Organization ID`.
  src/api/ADempiere/form/accouting.js
  src/store/modules/ADempiere/form/AcctViewer.js
Labels: bug, (WIN) Windows, (REC) Records, (FRM) Form

#2580 Fix: Upload file and associate to the import format.
  src/api/ADempiere/form/VFileImport.js
  src/components/ADempiere/FormDefinition/VFileImport/SelectFile/selectResource.vue
  src/store/modules/ADempiere/form/VFileImport.js
Labels: bug, (FRM) Form, Attachment

#2585 Fix: Export Sumary
  src/api/ADempiere/reportManagement/index.ts
  src/components/ADempiere/Report/Data/DataReport.vue
  src/components/ADempiere/ReportManager/Setup/options/reportSumary.vue
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: (RPT) Reports

#2586 Fix: Summary
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports

#2587 Fix: Width column on Report
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: enhancement, (RPT) Reports

#2588 feat: Reestructure UI to Field Management services.
  src/api/ADempiere/field/defaultValue.ts
  src/api/ADempiere/field/lookups.ts
  src/api/ADempiere/field/search/business-partner.ts
  src/api/ADempiere/field/search/index.js
  src/api/ADempiere/field/search/invoice.ts
  src/api/ADempiere/field/search/order.ts
  src/api/ADempiere/field/search/payment.ts
  src/api/ADempiere/field/search/product.ts
  src/api/ADempiere/field/zoom.js
  src/store/modules/ADempiere/defaultValueManager.js
  src/store/modules/ADempiere/lookupManager.js
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#2592 fix: Run Process or Generate Report.
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/processManager.js
  src/store/modules/ADempiere/reportManager.js
Labels: (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows

#2591 feat: Add zoom with button or record id.
  src/api/ADempiere/recordManagement/zoomWindows.ts
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/icons/svg/zoom-in.svg
  src/store/modules/ADempiere/zoomManager.js
Labels: enhancement, (WIN) Windows, (REC) Records, (UX) User Experience

#2594 fix: Loading `Notice` dashboard.
  src/components/ADempiere/Dashboard/notices/index.vue
  src/store/modules/ADempiere/form/notices.js
Labels: bug, dashboard

#2596 fix: Read only tab when table is view.
  src/components/ADempiere/DataTable/Components/ChangeRecord.vue
  src/components/ADempiere/TabManager/convenienceButtons/DeleteRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/NewRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/SaveRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/UndoChangeButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/index.vue
  src/utils/ADempiere/dictionary/window/index.js
Labels: bug, (WIN) Windows, (REC) Records

#2598 Process Data Import and Manage Files Uploaded to the Import Format
  src/api/ADempiere/form/VFileImport.js
  src/components/ADempiere/FormDefinition/VFileImport/SelectFile/index.vue
  src/components/ADempiere/FormDefinition/VFileImport/SelectFile/tableRecords.vue
  src/components/ADempiere/FormDefinition/VFileImport/SelectTable/charsetsList.vue
  src/components/ADempiere/FormDefinition/VFileImport/SelectTable/importFormatsList.vue
  src/components/ADempiere/FormDefinition/VFileImport/SelectTable/index.vue
  src/components/ADempiere/FormDefinition/VFileImport/index.vue
Labels: bug, (FRM) Form, Attachment

#2599 feat: Change search fields end-point.
  src/api/ADempiere/field/binary.js
  src/api/ADempiere/fields/accoutingCombination.js
  src/api/ADempiere/fields/binary.js
  src/api/ADempiere/fields/defaultValue.ts
  src/api/ADempiere/fields/generalGedger.js
  src/api/ADempiere/fields/location-address.ts
  src/api/ADempiere/fields/location.js
  src/api/ADempiere/fields/lookups.ts
  src/api/ADempiere/fields/preference.js
  src/api/ADempiere/fields/product-info.js
  src/api/ADempiere/fields/productAttribute.js
  src/api/ADempiere/fields/search/business-partner.ts
  src/api/ADempiere/fields/search/index.js
  src/api/ADempiere/fields/search/invoice.ts
  src/api/ADempiere/fields/search/order.ts
  src/api/ADempiere/fields/search/payment.ts
  src/api/ADempiere/fields/search/product.ts
  src/api/ADempiere/fields/warehouseLocator.js
  src/api/ADempiere/fields/zoom.js
  src/components/ADempiere/FieldDefinition/FieldAccountingCombination/Fields/SelectAccounting.vue
  src/components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria2.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  src/components/ADempiere/FieldDefinition/FieldOptions/PreferenceValue/index.vue
  src/components/ADempiere/FieldDefinition/FieldProductAttribute/detailAttributeInstance.vue
  src/components/ADempiere/FieldDefinition/FieldProductAttribute/listAttributeInstance.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/PanelForm/QueryCriteria/OrderField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/QueryCriteria/OrderField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/QueryCriteria/OrderField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/priceListVersionField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/productCategoryField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/productClassField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/productClassificationField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/productGroupField.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/QueryCriteria/vendorField.vue
  src/components/ADempiere/Form/ProductSearch/index.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/AddNewFieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/AddNewFieldLocation/mixinLocation.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/BillingFieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/BillingFieldLocation/mixinLocation.js
  src/components/ADempiere/Form/VPOS/BusinessPartner/billingAddressFieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/shippingAddressFieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/shippingFieldLocation/locationAddressForm.vue
  src/components/ADempiere/Form/VPOS/BusinessPartner/shippingFieldLocation/mixinLocation.js
  src/store/modules/ADempiere/defaultValueManager.js
  src/store/modules/ADempiere/field/accountingCombination.js
  src/store/modules/ADempiere/field/locations.js
  src/store/modules/ADempiere/field/productInfo.js
  src/store/modules/ADempiere/field/search/businessPartnerSearch.js
  src/store/modules/ADempiere/field/search/generalSearch.js
  src/store/modules/ADempiere/field/search/invoiceFieldSearch.js
  src/store/modules/ADempiere/field/search/orderFieldSearch.js
  src/store/modules/ADempiere/field/search/paymentFieldSearch.js
  src/store/modules/ADempiere/field/search/productFieldSearch.js
  src/store/modules/ADempiere/field/warehouseLocator.js
  src/store/modules/ADempiere/fieldDefinition.js
  src/store/modules/ADempiere/form/VPOS/customer.js
  src/store/modules/ADempiere/form/productSearch.js
  src/store/modules/ADempiere/lookupManager.js
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#2600 Fix: Font Report
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2603 fix: `Payment` search field load records.
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/QueryCriteria/bankAccount.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/panelFooter.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/usePayment.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/buttonPaymentsList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/fieldsListSearch.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/mixinPayment.js
  src/store/modules/ADempiere/field/search/paymentFieldSearch.js
  src/utils/ADempiere/dictionary/field/search/payment.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#2602 Fix: Validate report process
  src/components/ADempiere/ReportManager/Setup/options/refreshButton.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/reportManager.js
  src/utils/ADempiere/dictionary/report.js
Labels: bug, (RPT) Reports
