Repository solop-develop/frontend-core, pull requests merged in 2024-10, with the labels that each got.

#2714 Support Mnemonic command for Save and New record on panel
  src/components/ADempiere/TabManager/convenienceButtons/NewRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/components/ADempiere/TabManager/convenienceButtons/SaveRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/UndoChangeButton.vue
Labels: enhancement, (WIN) Windows, (REC) Records

#2710 Fix: Footer Search Criteria
  src/components/ADempiere/Report/Data/DataReport.vue
  src/components/ADempiere/ReportManager/Setup/options/downloadButtom.vue
  src/components/ADempiere/ReportManager/Setup/options/printFormat.vue
  src/components/ADempiere/ReportManager/Setup/options/refreshButton.vue
  src/components/ADempiere/ReportManager/Setup/options/reportSumary.vue
  src/components/ADempiere/ReportManager/Setup/options/reportViews.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
Labels: (RPT) Reports, (UX) User Experience

#2717 Support Mnemonic command for Save, Undo and New record in Table
  src/components/ADempiere/TabManager/convenienceButtons/NewRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/SaveRecordButton.vue
  src/components/ADempiere/TabManager/convenienceButtons/UndoChangeButton.vue
  src/components/ADempiere/TabManager/index.vue
Labels: bug, (WIN) Windows, (REC) Records

#2694 Fix: Financial Report Report With Report Engine
  src/components/ADempiere/Report/Data/DataReport.vue
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/utils/ADempiere/constants/report.js
Labels: bug, (RPT) Reports

#2723 Fix: Report
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2724 fix: 500 Pagination Report
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: bug, (RPT) Reports

#2720 Fix: AutoFocus in Panel New recourd cdc900
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
Labels: bug, (WIN) Windows

#2734 Fix: Validate Report Jasper
  src/components/ADempiere/ReportManager/Setup/options/printFormat.vue
  src/components/ADempiere/ReportManager/Setup/options/refreshButton.vue
  src/components/ADempiere/ReportManager/Setup/options/reportViews.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/views/ADempiere/Report/Report.vue
  src/views/ADempiere/Report/ReportEngine.vue
  src/views/ADempiere/Report/index.vue
Labels: bug, (RPT) Reports

#2736 Support to Resource Line Time
  package.json
  src/lang/ADempiere/en/component/calendar.js
  src/lang/ADempiere/es/component/calendar.js
  src/main.js
  src/router/modules/ADempiere/staticRoutes.js
  src/views/ADempiere/CalendarView/data-resource-time.js
  src/views/ADempiere/CalendarView/index.vue
  src/views/ADempiere/CalendarView/resourceTimelineView.vue
  yarn.lock
Labels: bug, (UX) User Experience, Attachment

#2737 fix: Logics with multiple same column names on same panel.
  src/store/modules/ADempiere/panel/actions.js
Labels: bug, (SB) Smart Browser, (ULP) UI Lookups

#2738 Fix: Trial Balance Report
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2739 fix: Filters in Legacy Report
  src/components/ADempiere/FieldDefinition/index.vue
  src/components/ADempiere/ReportManager/Setup/optionsReport.vue
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/ADempiere/report/reportRun.js
  src/views/ADempiere/Report/Report.vue
  src/views/ADempiere/Report/ReportEngine.vue
  src/views/ADempiere/Report/index.vue
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/ReportViewerEngine/index.vue
Labels: (RPT) Reports, (UX) User Experience

#2727 Fix: Width Table View
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: (WIN) Windows, (UX) User Experience

#2741 fix: `Dunning Run Entry` without print button.
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/reportManager.js
  src/utils/ADempiere/constants/report.js
  src/utils/ADempiere/dictionary/report/financialReport.ts
Labels: bug, (RPT) Reports, (WIN) Windows

#2758 Fix: Style in Product Search
  src/components/ADempiere/Form/ProductSearch/index.vue
Labels: (UX) User Experience

#2747 fix: Refresh parent tab with refresh line.
  src/components/ADempiere/TabManager/convenienceButtons/SaveRecordButton.vue
  src/components/ADempiere/TabManager/index.vue
  src/utils/ADempiere/dictionary/window/index.js
Labels: bug, (WIN) Windows, (REC) Records

#2760 Fix: Zoom Search Product
  src/components/ADempiere/Form/ProductSearch/index.vue
Labels: enhancement, (WIN) Windows, (FRM) Form

#2732 Error in Business Partner Search Type Field
  src/store/modules/ADempiere/field/search/businessPartnerSearch.js
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#2761 feat: Add Filter to List Issues
  src/api/ADempiere/user-interface/component/issue.js
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/lang/ADempiere/en/form/issues.js
  src/lang/ADempiere/es/form/issues.js
  src/store/modules/ADempiere/form/issueManagement.js
Labels: bug, enhancement, (FRM) Form

#2765 Fix: Style Product Search
  src/components/ADempiere/Form/ProductSearch/index.vue
Labels: (FRM) Form, (UX) User Experience

#2766 Fix: Style `Point Of Sales` form.
  src/components/ADempiere/Form/VPOS2/FooterOrder/ButtonGroupOptions.vue
  src/components/ADempiere/Form/VPOS2/FooterOrder/InfoOrder.vue
  src/components/ADempiere/Form/VPOS2/FooterOrder/OptionsList.vue
  src/components/ADempiere/Form/VPOS2/FooterOrder/index.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/index.vue
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2768 fix: Disable button when is process.
  src/components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  src/utils/ADempiere/dictionary/window/index.js
Labels: bug, (PRC) Processes, (RPT) Reports, (WIN) Windows, (REC) Records, (UX) User Experience

#2767 Add Filters and Scroll
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/components/ADempiere/Form/Issues/component/Comment.vue
Labels: (FRM) Form

#2773 Fix: Zoom in Code Search Product
  src/components/ADempiere/Form/ProductSearch/index.vue
Labels: enhancement, (FRM) Form

#2792 Fix: Color In Cells
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports

#2793 add a check to see all
  src/components/ADempiere/TabManager/AdvancedTabQuery.vue
  src/lang/ADempiere/en/window.js
  src/lang/ADempiere/es/window.js
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#2790 feat: Overwrite display type on reference to `Button` fields.
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldOptions/DocumentStatus/index.vue
  src/components/ADempiere/Form/AcctViewer/index.vue
  src/utils/ADempiere/dictionaryUtils.js
Labels: bug, (SB) Smart Browser, (WIN) Windows, (REC) Records, (ULP) UI Lookups, (UX) User Experience

#2791 Enable Workflow Actions Button Panel
  src/components/ADempiere/Form/WorkflowActivity/index.vue
Labels: bug, enhancement, (WFL) Workflows, (FRM) Form

#2788 Fix: Notify Finance Report
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2799 Fix: Width Column SB
  src/components/ADempiere/DataTable/Browser/index.vue
  src/utils/ADempiere/references.js
Labels: (SB) Smart Browser, (UX) User Experience

#2798 Fix: Hidden Column Budget
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
Labels: (FRM) Form, (UX) User Experience

#2726 fix: Parameters In Window Report
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: bug, (RPT) Reports

#2797 Fix: Hidden Arrow Report Enginer
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports

#2802 Fix: Width Column Windown
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: (WIN) Windows, (UX) User Experience

#2804 Fix: Terminal Pvo
  src/store/modules/ADempiere/form/VPOS/index.js
Labels: (POS) Point Of Sales, (UX) User Experience

#2805 Fix: Smaller Default Font Size
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports, (UX) User Experience

#2789 Support to Search Value in Issues Filters
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
Labels: bug, enhancement, (FRM) Form

#2800 Reduce the Number of Requests at the Point of Sales
  src/components/ADempiere/Form/VPOS2/FooterOrder/OptionsList.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/editLine/editQtyEnteredField.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/editLine/index.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/index.vue
  src/components/ADempiere/Form/VPOS2/Options/salesOrder.vue
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
  src/store/modules/ADempiere/form/VPOS/customer.js
  src/store/modules/ADempiere/form/VPOS/fieldsCollections.js
  src/store/modules/ADempiere/form/VPOS/index.js
  src/store/modules/ADempiere/form/VPOS/lines.js
  src/store/modules/ADempiere/form/VPOS/order.js
  src/store/modules/ADempiere/pointOfSales/point/actions.js
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2808 Copy Output to Process History
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
  src/views/ADempiere/ProcessActivity/processActivity.js
Labels: bug, (PRC) Processes, (FRM) Form

#2807 Fix: Download Legacy Report
  src/components/ADempiere/ReportManager/Setup/optionsReport.vue
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: (RPT) Reports, (UX) User Experience, Attachment

#2809 Improve column size in the table
  src/components/ADempiere/DataTable/Components/CellEditInfo.vue
  src/components/ADempiere/FieldDefinition/FieldDate.vue
  src/components/ADempiere/FieldDefinition/FieldNumber.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/index.vue
  src/components/ADempiere/FieldDefinition/FieldSelect/index.vue
  src/components/ADempiere/FieldDefinition/FieldText.vue
  src/components/ADempiere/FieldDefinition/FieldTime.vue
  src/components/ADempiere/FieldDefinition/FieldYesNo/SelectTemplate.vue
  src/components/ADempiere/FieldDefinition/FieldYesNo/SwitchTemplate.vue
  src/components/ADempiere/FieldDefinition/FieldYesNo/index.vue
  src/components/ADempiere/FieldDefinition/index.vue
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#2811 Fix: Download Report
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports, Attachment

#2810 Fix: Page Size on Window records
  src/components/ADempiere/TabManager/TabPanel/modeDesktop.vue
Labels: (WIN) Windows, (REC) Records, (UX) User Experience

#2813 Fix: Transformer Output Flow in File
  src/store/modules/ADempiere/reportManager.js
Labels: (RPT) Reports, Attachment

#2819 Fix: Financial Report Notification
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2820 feat: Add `Role` on `Export Dictionary` form.
  src/components/ADempiere/Process/ExportDictionaryDefinition.vue
  src/lang/ADempiere/en/page/process/exportDictionary.js
  src/lang/ADempiere/es/page/process/exportDictionary.js
Labels: (PRC) Processes, (FRM) Form

#2821 fix: Undefined `iconClass` on menu search.
  src/components/HeaderSearch/index.vue
  src/router/modules/ADempiere/staticRoutes.js
  src/views/dashboard/admin/index.vue
Labels: bug, (MEN) Menues

#2822 fix: Hidden buttons fields on `Advanced Query`.
  src/components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#2827 fix: `Is Avanced Query` button reference.
  src/utils/ADempiere/dictionaryUtils.js
Labels: bug, (WIN) Windows, (REC) Records

#2825 Fix: Posted Credit Amount
  src/components/ADempiere/Form/AcctViewer/ActionsFooter/index.vue
  src/components/ADempiere/Form/AcctViewer/TableRecords/index.vue
  src/components/ADempiere/Form/AcctViewer/TableRecords/sourceColumns.vue
Labels: bug, (WIN) Windows, (FRM) Form

#2829 Field size in grid mode
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/index.vue
Labels: bug, (WIN) Windows

#2832 Fix: Download Legacy Report
  src/store/modules/ADempiere/reportManager.js
Labels: (RPT) Reports

#2828 Validate POS
  src/store/modules/ADempiere/form/VPOS/index.js
Labels: bug, (POS) Point Of Sales

#2835 Fix: Download Legacy Report v2
  src/api/ADempiere/file-management/resource-reference.ts
  src/store/modules/ADempiere/reportManager.js
Labels: (RPT) Reports

#2839 Fix: MarkDown Html
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: (RPT) Reports

#2843 Support to Filter Issues All
  src/api/ADempiere/user-interface/component/issue.js
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/store/modules/ADempiere/form/issueManagement.js
Labels: bug, (FRM) Form, (UX) User Experience

#2844 Fix: Clear Parameters
  src/components/ADempiere/ReportManager/Setup/options/downloadButtom.vue
  src/views/ADempiere/ReportViewerEngine/dialog/contactSend.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/typeNotify.vue
Labels: bug, (RPT) Reports, Attachment

#2845 Fix: Summary Children
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports, (UX) User Experience

#2846 Fix: Default rounding in fields
  src/components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  src/utils/ADempiere/constants/systemColumns.js
  src/utils/ADempiere/formatValue/numberFormat.js
  src/utils/ADempiere/valueFormat.js
Labels: bug, (ULP) UI Lookups

#2847 Remove Console
  src/components/ADempiere/Form/VPOS2/MainOrder/index.vue
Labels: bug, (POS) Point Of Sales

#2848 Apply Precision in the fields
  src/components/ADempiere/FieldDefinition/FieldNumber.vue
  src/utils/ADempiere/formatValue/numberFormat.js
Labels: bug, (ULP) UI Lookups

#2851 Add Image to User to Assigned
  src/components/ADempiere/FormDefinition/IssueManagement/issueAvatar.vue
  src/store/modules/ADempiere/form/issueManagement.js
Labels: bug, (FRM) Form, Attachment

#2852 Add Image to User to Assigned
  src/api/ADempiere/user-interface/component/issue.js
  src/components/ADempiere/DataTable/Components/CustomPagination.vue
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/components/ADempiere/FormDefinition/IssueManagement/IssuesList/issueRow.vue
  src/components/ADempiere/FormDefinition/IssueManagement/issueAvatar.vue
  src/store/modules/ADempiere/form/issueManagement.js
  src/utils/ADempiere/constants/resoucer.ts
Labels: bug, (FRM) Form

#2857 fix: Logics on Reports and Process.
  src/components/ADempiere/FieldDefinition/index.vue
  src/lang/ADempiere/en/operators.ts
  src/lang/ADempiere/es/operators.ts
  src/store/modules/ADempiere/dictionary/report/actions.js
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/panel/actions.js
  src/utils/ADempiere/dictionary/process.js
  src/utils/ADempiere/dictionaryUtils.js
Labels: (PRC) Processes, (RPT) Reports, (ULP) UI Lookups

#2859 Add Loading in Issues All
  src/components/ADempiere/Form/Issues/ListIssues/index.vue
  src/store/modules/ADempiere/form/issueManagement.js
Labels: bug, (REC) Records, (FRM) Form

#2863 Fix Paginations Page Size
  src/store/modules/ADempiere/form/issueManagement.js
Labels: bug, (REC) Records, (FRM) Form

#2866 Fix: Does not set the Value in Grid mode
  src/components/ADempiere/PanelDefinition/StandardPanel.vue
  src/components/ADempiere/TabManager/index.vue
Labels: bug, (ULP) UI Lookups

#2867 Fix: Multiple requests when viewing the image
  src/components/PanThumb/index.vue
  src/layout/components/Navbar.vue
  src/layout/components/ProfilePreview.vue
  src/layout/components/Sidebar/Logo.vue
Labels: bug, (CIO) Code Improvement or Optimization, (UX) User Experience, Attachment

#2870 Fix: Point of Sale with other windows open VUE collapses
  src/components/ADempiere/Form/VPOS2/FooterOrder/ButtonGroupOptions.vue
  src/store/modules/ADempiere/form/VPOS/index.js
  src/store/modules/ADempiere/form/VPOS/order.js
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2872 Fix: InstanceId Report
  src/api/ADempiere/reportManagement/index.ts
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2873 fix: Save tab entity undefined attributes.
  src/store/modules/ADempiere/persistence.js
Labels: bug, (WIN) Windows, (REC) Records

#2874 Support Service Get Currency
  src/api/ADempiere/system-core.js
  src/components/ADempiere/FieldDefinition/FieldNumber.vue
  src/store/modules/user.js
Labels: bug, (REC) Records, (ULP) UI Lookups

#2875 feat: Add `Display Type` on field info.
  src/components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  src/lang/ADempiere/en/field/displayType.ts
  src/lang/ADempiere/en/field/index.js
  src/lang/ADempiere/es/field/displayType.ts
  src/lang/ADempiere/es/field/index.js
  src/utils/ADempiere/references.js
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#2871 feat: Reports in Batch
  src/api/ADempiere/reportManagement/index.ts
  src/components/ADempiere/Report/Data/Dialog.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/ReportViewer/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: enhancement, (RPT) Reports, Attachment

#2876 Fix Point of Sale with other open windows VUE collapses
  src/store/modules/ADempiere/form/VPOS/index.js
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2880 fix: Duplicated `Export Dictionary` process.
  src/components/ADempiere/Process/ExportDictionaryDefinition.vue
  src/components/HeaderSearch/index.vue
  src/router/modules/ADempiere/staticRoutes.js
Labels: bug, (PRC) Processes, (MEN) Menues, (SE) Security, (FRM) Form

#2878 Fix: Show Trial Balance Columns
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
Labels: bug, (FRM) Form, (UX) User Experience

#2881 Fix: Default Image In Requests
  src/components/ADempiere/FormDefinition/IssueManagement/issueAvatar.vue
  src/utils/ADempiere/resource.js
Labels: bug, (FRM) Form, Attachment

#2877 Fix: Flag of The Process
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2885 Fix: Highest Reporting Line
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2887 Fix: About Pestana Daughter
  src/components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
  src/components/ADempiere/TabManager/tabChild.vue
Labels: bug, (WIN) Windows, (REC) Records

#2888 Fix: Download Report .Zip
  src/api/ADempiere/reportManagement/index.ts
  src/lang/ADempiere/en/report.js
  src/lang/ADempiere/es/report.js
Labels: bug, (RPT) Reports, Attachment

#2889 Fix: View different reports at the same time
  src/router/modules/ADempiere/staticRoutes.js
  src/store/modules/ADempiere/reportManager.js
  src/store/modules/tagsView.js
  src/utils/ADempiere/constants/report.js
  src/views/ADempiere/ReportViewerEngine/index.vue
Labels: bug, (RPT) Reports

#2892 Fix: Instance In Report Filter
  src/api/ADempiere/reportManagement/index.ts
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2893 Fix: InstanceId In Report Engine
  src/api/ADempiere/reportManagement/index.ts
  src/store/modules/ADempiere/reportManager.js
Labels: (RPT) Reports

#2895 Fix: FileType In Report
  src/api/ADempiere/reportManagement/index.ts
  src/components/ADempiere/Report/Data/Dialog.vue
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports, Attachment

#2896 Fix: Column Width In Window
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#2890 feat: Generate Report From Zoom
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
  src/lang/ADempiere/en/form/WTrialBalance.js
  src/lang/ADempiere/es/form/WTrialBalance.js
Labels: enhancement, (RPT) Reports, (FRM) Form

#2897 Add Focus Lost to Commant Save
  src/components/ADempiere/TabManager/index.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#2899 Fix: Sequence Changes
  src/store/modules/ADempiere/dictionary/window/actions.js
Labels: (WIN) Windows, (ULP) UI Lookups

#2898 Fix: Name And Value In Zoom
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
Labels: (FRM) Form, (UX) User Experience

#2900 Fix: Image Logo Menu
  src/components/ADempiere/TabManager/index.vue
  src/layout/components/Sidebar/Logo.vue
Labels: Attachment

#2902 Fix: Table Window
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: (WIN) Windows

#2904 Fix: Corrections Point of Sale
  src/components/ADempiere/Form/VPOS2/Collection/Charge/index.vue
  src/components/ADempiere/Form/VPOS2/FooterOrder/OptionsList.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/index.vue
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/panel.vue
  src/store/modules/ADempiere/form/VPOS/options.js
Labels: bug, (POS) Point Of Sales

#2910 Open cash drawer with payment in 0
  src/components/ADempiere/Form/VPOS2/Options/cashManagement/cashOpening/panel.vue
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2912 Fix: Line Height Window
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: (WIN) Windows, (UX) User Experience
