Repository solop-develop/frontend-core, pull requests merged in 2024-09, with the labels that each got.

#2609 feat: Improve field search.
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/panelFooter.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/PanelForm/useBusinessPartner.js
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/PanelForm/panelFooter.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/InvoiceInfo/mixinInvoice.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/QueryCriteria/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/panelFooter.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/PanelForm/useOrder.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/businessPartnersList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Order/mixinOrder.js
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/QueryCriteria/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/index.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/Payment/mixinPayment.js
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/PanelForm/tableRecords.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/buttonList.vue
  src/components/ADempiere/FieldDefinition/FieldSearch/ProductInfo/index.vue
  src/store/modules/ADempiere/field/accountingCombination.js
  src/store/modules/ADempiere/field/search/businessPartnerSearch.js
  src/store/modules/ADempiere/field/search/generalSearch.js
  src/store/modules/ADempiere/field/search/invoiceFieldSearch.js
  src/store/modules/ADempiere/field/search/orderFieldSearch.js
  src/store/modules/ADempiere/field/search/paymentFieldSearch.js
  src/store/modules/ADempiere/field/search/productFieldSearch.js
  src/utils/ADempiere/dictionary/field/search/invoice.js
  src/utils/ADempiere/dictionary/field/search/order.js
Labels: enhancement, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#2611 Fix: Load In News
  src/store/modules/ADempiere/form/notices.js
Labels: dashboard, (UX) User Experience

#2612 Fix: Parameters in report
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports

#2613 Fix: Hidden Clear Button
  src/components/ADempiere/FieldDefinition/FieldImage.vue
Labels: enhancement, Attachment

#2621 Fix: Window report with legacy
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/report/reportRun.js
Labels: (RPT) Reports

#2617 Loading Complete Order
  src/components/ADempiere/Form/VPOS2/Options/salesOrder.vue
Labels: (FRM) Form, (POS) Point Of Sales

#2629 Change EndPoint the Resource
  config/default.json
  src/api/ADempiere/file-management/resource-reference.ts
  src/api/ADempiere/user-interface/component/resource.js
  src/components/ADempiere/FieldDefinition/FieldImage.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/FileShare.vue
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/listView.vue
  src/store/modules/ADempiere/reportManager.js
  src/store/modules/user.js
  src/utils/ADempiere/resource.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: bug, Attachment

#2632 Fix: Send In Search Criteria
  src/api/ADempiere/file-management/resource-reference.ts
  src/components/ADempiere/ReportManager/Setup/options/downloadButtom.vue
  src/store/modules/ADempiere/reportManager.js
  src/views/ADempiere/Report/index.vue
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: bug, (RPT) Reports

#2635 Zoom in to Records from Links Report
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports, (WIN) Windows

#2637 fix: Save and set `Accouting Combination` field.
  src/api/ADempiere/userInterface/entities.ts
  src/components/ADempiere/FieldDefinition/FieldAccountingCombination/Fields/SelectAccounting.vue
  src/components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  src/components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria2.vue
  src/store/modules/ADempiere/persistence.js
  src/utils/ADempiere/dictionary/field/accoutingCombination.js
  src/utils/ADempiere/recordUtil.js
  src/utils/ADempiere/valueUtils.js
Labels: bug, (WIN) Windows, (REC) Records, (FRM) Form

#2636 Fix: Order By Window
  src/api/ADempiere/userInterface/entities.ts
  src/components/ADempiere/DataTable/Windows/index.vue
  src/store/modules/ADempiere/windowManager.js
Labels: bug, (WIN) Windows, (REC) Records

#2633 Action Process DUPLICATES if double Click is made
  src/components/ADempiere/ModalDialog/index.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/store/modules/ADempiere/processManager.js
Labels: bug, (PRC) Processes, (RPT) Reports

#2638 Fix: Order By fields window.
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: (WIN) Windows, (REC) Records

#2640 fix: Update with new null values.
  src/api/ADempiere/userInterface/entities.ts
  src/api/ADempiere/userInterface/window.ts
  src/store/modules/ADempiere/calloutManager.js
  src/store/modules/ADempiere/persistence.js
Labels: bug, (WIN) Windows, (REC) Records

#2639 Resource End-Point
  src/api/ADempiere/file-management/resource-reference.ts
Labels: bug, Attachment

#2641 Fix: Size Of Operators
  src/components/ADempiere/FieldDefinition/FieldOptions/ComparisonOperator.vue
  src/lang/ADempiere/en/operators.ts
  src/lang/ADempiere/es/operators.ts
Labels: (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (UX) User Experience

#2643 fix: Save location address field.
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/countriesListField.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/index.vue
  src/components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm/regionsListField.vue
  src/utils/ADempiere/dictionary/field/locationAddress.js
Labels: bug, (ULP) UI Lookups

#2642 fix: Disable upload button to attachment.
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  src/lang/ADempiere/en/component/attachment.js
  src/lang/ADempiere/es/component/attachment.js
Labels: bug, Attachment

#2644 fix: Open SB from button or process associated.
  src/api/ADempiere/dictionary/smart-browser.js
  src/components/ADempiere/FieldDefinition/FieldButton.vue
  src/store/modules/ADempiere/dictionary/browser/actions.js
  src/utils/ADempiere/dictionary/window/actionsMenu.js
  src/views/ADempiere/Browser/index.vue
Labels: bug, (PRC) Processes, (SB) Smart Browser, (WIN) Windows

#2646 Fix: Hidden Parent Level 2
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2647 Validate Exist Process
  src/components/ADempiere/Process/ExportDictionaryDefinition.vue
Labels: bug, (MEN) Menues, (FRM) Form

#2648 fix: Duplicated resource `/api/api`.
  src/api/ADempiere/file-management/resource-reference.ts
  src/components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  src/utils/ADempiere/resource.js
  src/views/ADempiere/ReportViewerEngine/dialog/index.vue
Labels: bug, Attachment

#2649 Fix: Sumary Report
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2651 Fix: Endpoint Location
  src/api/ADempiere/fields/warehouseLocator.js
Labels: bug

#2653 Fix: Send OrderBy Change Page
  src/store/modules/ADempiere/windowManager.js
Labels: (WIN) Windows, (REC) Records

#2656 fix: Height Table Report
  src/components/ADempiere/Report/Data/DataReport.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/store/modules/ADempiere/reportManager.js
Labels: bug, (RPT) Reports, (UX) User Experience

#2657 Clean zoom when performing an advanced search
  src/components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (WIN) Windows, (REC) Records

#2660 Add Methods isDisabledDone
  src/store/modules/ADempiere/dictionary/browser/actions.js
Labels: bug, (PRC) Processes, (RPT) Reports

#2662 Duplicate action in Associated Processes in window
  src/store/modules/ADempiere/dictionary/window/actions.js
  src/store/modules/ADempiere/dictionary/window/getters.js
  src/store/modules/ADempiere/dictionary/window/mutations.js
  src/store/modules/ADempiere/dictionary/window/state.js
Labels: bug, (PRC) Processes, (WIN) Windows

#2663 Fix: Value Report Enginer
  src/components/ADempiere/Report/Data/DataCells.vue
Labels: bug, (RPT) Reports

#2666 Fix: Report Engine Version
  src/api/ADempiere/common/index.ts
  src/icons/svg/reportEngine.svg
  src/lang/ADempiere/en/index.js
  src/lang/ADempiere/es/index.js
  src/store/modules/user.js
  src/views/profile/components/InfoUser.vue
Labels: (RPT) Reports, (UX) User Experience

#2669 Fix: Change line quantities
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/editLine/index.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/index.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/OptionLine/infoLine.vue
  src/components/ADempiere/Form/VPOS2/MainOrder/index.vue
Labels: bug, (FRM) Form, (POS) Point Of Sales

#2681 Fix: Font Size Report Enginer
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports, (UX) User Experience

#2670 Fix: Hidden Type Report
  src/components/ADempiere/Report/Data/DataReport.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/views/ADempiere/ReportViewerEngine/reportPanel.vue
Labels: (RPT) Reports, (UX) User Experience

#2691 fix: navigable trial balance table width
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
Labels: bug, (FRM) Form

#2692 Fix: View Sorting Considers Filters
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (WIN) Windows, (REC) Records

#2699 fix: `Payment Rule` field with Button as List display type.
  src/utils/ADempiere/dictionaryUtils.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#2700 Support to Resource Line Time
  package.json
  src/lang/ADempiere/en/component/calendar.js
  src/lang/ADempiere/es/component/calendar.js
  src/main.js
  src/router/modules/ADempiere/staticRoutes.js
  src/views/ADempiere/CalendarView/data-resource-time.js
  src/views/ADempiere/CalendarView/index.vue
  src/views/ADempiere/CalendarView/resourceTimelineView.vue
  yarn.lock
Labels: enhancement, question, (FRM) Form

#2703 Fix: Navigable Trial Balance Design
  src/components/ADempiere/FormDefinition/WTrialBalance/index.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/accounting.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/balance.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/cube.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/index.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/organization.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/period.vue
  src/components/ADempiere/FormDefinition/WTrialBalance/options/showButtom.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
  src/store/modules/wTrialBalance.js
Labels: bug, (FRM) Form

#2684 Fix: Zoom Report
  src/components/ADempiere/Report/Data/DataCells.vue
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: bug, (RPT) Reports

#2682 Fix: Width Column Report Enginer
  src/components/ADempiere/Report/Data/DataReport.vue
Labels: (RPT) Reports, (UX) User Experience

#2704 Fix: Refresh Report From Side
  src/components/ADempiere/Report/Data/DataReport.vue
  src/components/ADempiere/ReportManager/Setup/options/reportSumary.vue
  src/components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  src/components/ADempiere/TabManager/convenienceButtons/PrintProcess.vue
Labels: (RPT) Reports, (UX) User Experience

#2706 FIx: Process History does not show history
  src/views/ADempiere/ProcessActivity/modeDesktop.vue
  src/views/ADempiere/ProcessActivity/processActivity.js
Labels: bug, (PRC) Processes, (RPT) Reports

#2707 Fix: Width Column View
  src/components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#2708 Fix: Width Column SB
  src/components/ADempiere/DataTable/Browser/index.vue
Labels: (SB) Smart Browser, (UX) User Experience
